# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "exctl"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joseph Wecker"]
  s.date = "2013-11-13"
  s.description = "Allows you to create a command-line dispatcher for a project to consolidate dev, release, and runtime workflows."
  s.email = "joseph.wecker@gmail.com"
  s.executables = ["exctl"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".attic/c_src/get-version.c",
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "OPERUM.md",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/exctl",
    "exctl.gemspec",
    "lib/exctl.rb",
    "lib/exctl/cli.rb",
    "lib/exctl/dispatch.rb",
    "lib/shorthand.rb",
    "notes.md",
    "templates/default-dot-commands.erb",
    "templates/dispatch-wrapper.erb",
    "test/helper.rb",
    "test/test_exctl.rb"
  ]
  s.homepage = "http://github.com/josephwecker/exctl"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Project-specific command-line task dispatcher generator."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
  end
end

